version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - database
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  database:
    image: postgres:12.0-alpine
    volumes:
      - notepad_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notepad

volumes:
    notepad_data:
